#19: feat: Created a new component "ActivityList" #19: add: added a n…
arifjehoh/bored-activity pull request #25
Opened 2021-12-05 13:00 UTC by Abdullahtr249

…ew component "ActivityList" to App.vue

2021-12-05 15:03 UTC, arifjehoh requested changes

2021-12-05 15:03 UTC, arifjehoh commented on src/App.vue
> +  <div id=app>
Why have you added `id=app`, it wasn't need before...

2021-12-05 15:03 UTC, arifjehoh commented on src/components/ActivityList.vue
> +</script>
Make sure you use `2 space` per indentation.

2021-12-05 15:03 UTC, arifjehoh commented on src/components/ActivityList.vue
> +        })
Can we export this way of using the API to a Javascript file? For more dynamically usage of the API Calls, just like how we did in the DinnerModel(DishSource)

2021-12-05 16:12 UTC, Abdullahtr249 commented on src/App.vue
> +  <div id=app>
fixt. I tried to test the cod

2021-12-05 16:24 UTC, mhaao commented on src/components/ActivityList.vue
> +        })
can you test this first? Because the API key was different and I tried and I hade ERORR   :(

2021-12-06 15:26 UTC, arifjehoh approved these changes
Good work! I Fixed the issue in some of the files.

2021-12-06 15:27 UTC, merged